server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/catering?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zohar001
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
storage:
  storagePath: E:\tmp\pic